package com.reiryoku_expansion.hokora;

import java.util.Collections;
import java.util.EnumMap;
import java.util.Locale;
import java.util.Map;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonSyntaxException;
import com.iwaliner.urushi.util.ElementType;
import com.reiryoku_expansion.ReiryokuElement;

import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.crafting.Ingredient;
import net.minecraft.world.item.crafting.RecipeManager;

/**
 * Runtime cache for the datapack-driven Hokora (神龛) fuel configuration.
 * The map is replaced atomically on every datapack reload; block entity code
 * only reads it, so no locking is needed. Recipe-type entries take precedence
 * over the legacy {@code reiryoku_hokora} folder format.
 */
public final class HokoraFuelConfig {

    private static volatile Map<ElementType, FuelEntry> LEGACY = Map.of();
    private static volatile Map<ElementType, FuelEntry> RECIPES = Map.of();

    private HokoraFuelConfig() {
    }

    /** Returns the configured fuel item for the element, or null to keep the mod default. */
    public static Item getFuel(ElementType element) {
        FuelEntry entry = entry(element);
        return entry == null ? null : entry.item;
    }

    /** True when an entry exists for the element (either recipe or legacy config). */
    public static boolean isConfigured(ElementType element) {
        return entry(element) != null;
    }

    /** Tests a stack against the element's configured fuel ingredient (supports tags / multiple items). */
    public static boolean isFuel(ElementType element, ItemStack stack) {
        FuelEntry entry = entry(element);
        return entry != null && entry.ingredient.test(stack);
    }

    /** Returns the configured Reiryoku amount per conversion, or null for the mod default (5). */
    public static Integer getReiryokuAmount(ElementType element) {
        FuelEntry entry = entry(element);
        return entry == null ? null : entry.reiryoku;
    }

    /** Returns the configured cooldown in ticks, or null for the mod default (100). */
    public static Integer getCooldown(ElementType element) {
        FuelEntry entry = entry(element);
        return entry == null ? null : entry.cooldown;
    }

    public static void reloadLegacy(EnumMap<ElementType, FuelEntry> fuels) {
        LEGACY = Collections.unmodifiableMap(new EnumMap<>(fuels));
    }

    public static void reloadRecipes(EnumMap<ElementType, FuelEntry> fuels) {
        RECIPES = Collections.unmodifiableMap(new EnumMap<>(fuels));
    }

    /**
     * Reads Hokora fuel recipes from the server recipe manager. This is the
     * authoritative source: it contains both on-disk
     * {@code data/<ns>/recipes/*.json} files and recipes generated by KubeJS
     * scripts (which are injected at runtime and never appear on disk).
     */
    public static void reloadFromRecipeManager(RecipeManager manager) {
        EnumMap<ElementType, FuelEntry> fuels = new EnumMap<>(ElementType.class);
        for (HokoraFuelRecipe recipe : manager.m_44013_(HokoraFuelRecipe.TYPE)) { // byType
            if (recipe.getElement() == null) {
                continue; // defensive; serializer validation rejects null elements at load time
            }
            Ingredient ingredient = recipe.getFuelIngredient();
            ItemStack[] stacks = ingredient.m_43908_(); // getItems
            if (stacks.length == 0) {
                continue;
            }
            fuels.put(recipe.getElement(),
                    new FuelEntry(ingredient, stacks[0].m_41720_(), recipe.getReiryoku(), recipe.getCooldown()));
        }
        reloadRecipes(fuels);
    }

    /** Parses "wood"/"fire"/... element names; returns null for unknown names. */
    public static ElementType parseElement(String name) {
        try {
            return ReiryokuElement.valueOf(name.toUpperCase(Locale.ROOT)).toUrushi();
        } catch (IllegalArgumentException e) {
            return null;
        }
    }

    /**
     * Parses a recipe-style ingredient. Forge's {@code Ingredient.fromJson}
     * rejects a bare string, so plain string ids are wrapped into an object
     * first (matching how recipe files are normally written).
     */
    public static Ingredient parseIngredient(JsonElement json) {
        if (json.isJsonPrimitive()) {
            JsonObject object = new JsonObject();
            object.addProperty("item", json.getAsString());
            json = object;
        }
        return Ingredient.m_43917_(json); // fromJson
    }

    /**
     * Reads a positive int field, using {@code defaultValue} when absent.
     * Throws {@link JsonSyntaxException} (including the recipe id and field
     * name) for non-numeric, non-positive or overflowing values, so invalid
     * data is rejected during datapack / KubeJS recipe reload instead of
     * surfacing as a runtime error.
     */
    public static int parsePositiveInt(JsonObject json, String field, int defaultValue, ResourceLocation id) {
        if (!json.has(field)) {
            return defaultValue;
        }
        long value;
        try {
            value = json.get(field).getAsLong();
        } catch (NumberFormatException e) {
            throw new JsonSyntaxException(
                    "Invalid '" + field + "' value '" + json.get(field) + "' in hokora fuel recipe '" + id + "'", e);
        }
        if (value <= 0) {
            throw new JsonSyntaxException(
                    "'" + field + "' must be > 0 in hokora fuel recipe '" + id + "', got " + value);
        }
        if (value > Integer.MAX_VALUE) {
            throw new JsonSyntaxException(
                    "'" + field + "' is too large in hokora fuel recipe '" + id + "': " + value);
        }
        return (int) value;
    }

    private static FuelEntry entry(ElementType element) {
        FuelEntry recipe = RECIPES.get(element);
        return recipe != null ? recipe : LEGACY.get(element);
    }

    public static final class FuelEntry {
        /** Full configured ingredient; may match multiple items (tags, arrays). */
        public final Ingredient ingredient;
        /** First matching item, used as the comparison target by the mixin. */
        public final Item item;
        public final int reiryoku;
        public final int cooldown;

        public FuelEntry(Ingredient ingredient, Item item, int reiryoku, int cooldown) {
            this.ingredient = ingredient;
            this.item = item;
            this.reiryoku = reiryoku;
            this.cooldown = cooldown;
        }
    }
}
