package com.reiryoku_expansion;

import com.reiryoku_expansion.ae2.ReiryokuAE2Integration;
import com.reiryoku_expansion.hokora.HokoraFuelConfig;
import com.reiryoku_expansion.hokora.HokoraFuelRecipes;
import com.reiryoku_expansion.hokora.HokoraFuelReloadListener;

import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.AddReloadListenerEvent;
import net.minecraftforge.event.OnDatapackSyncEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.fml.ModList;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Bridges Urushi's Reiryoku (灵力) system into the pack:
 * <ul>
 *   <li>Data-driven Hokora (神龛) fuel conversion (mixin + datapack recipes),
 *       always enabled.</li>
 *   <li>KubeJS recipe schemas for Hokora fuel and Urushi element crafting,
 *       active whenever KubeJS is present.</li>
 *   <li>AE2 integration (cells, key type, bus strategies) - only registered
 *       when AE2 is loaded, so the mod works without AE2 too.</li>
 * </ul>
 */
@Mod("reiryoku_expansion")
public class ReiryokuExpansion {

    public static final String MODID = "reiryoku_expansion";

    private static final Logger LOGGER = LoggerFactory.getLogger("reiryoku_expansion");

    public ReiryokuExpansion() {
        IEventBus modBus = FMLJavaModLoadingContext.get().getModEventBus();

        // Recipe serializer for the datapack/KubeJS Hokura fuel recipes.
        HokoraFuelRecipes.initialize(modBus);

        // Hokora fuel config: legacy reiryoku_hokora folder...
        MinecraftForge.EVENT_BUS.addListener((AddReloadListenerEvent event) ->
                event.addListener(new HokoraFuelReloadListener()));
        // ...plus recipe-type entries read from the recipe manager after every
        // datapack sync (world join and /reload). This also picks up recipes
        // generated by KubeJS scripts, which never exist on disk.
        MinecraftForge.EVENT_BUS.addListener((OnDatapackSyncEvent event) ->
                HokoraFuelConfig.reloadFromRecipeManager(event.getPlayerList().m_7873_().m_129894_()));

        if (ModList.get().isLoaded("ae2")) {
            ReiryokuAE2Integration.init(modBus);
        } else {
            LOGGER.info("Applied Energistics 2 not detected - ME Reiryoku storage integration disabled");
        }
    }

    public static ResourceLocation id(String path) {
        return new ResourceLocation(MODID, path);
    }
}
